site_title: Kent Maps
gh_path: https://kent-map.github.io
root_essay: https://kg.jstor.org/wiki/Kent:Essays
banner_image: https://kg.jstor.org/w/images/c/cc/Viking_Bay,_Broadstairs.jpg
app_version: 0.2.0
visual_essays_version: 0.3.0
context: kent-maps